# Generated by Django 4.2.7 on 2023-11-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_simulador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageYaab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='solicitud/')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='solicitud/')),
            ],
            options={
                'verbose_name': 'imagen_yaab',
            },
        ),
    ]
