# Generated by Django 4.2.7 on 2023-11-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_imageyaab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageyaab',
            name='imagen_perfil',
        ),
    ]
