# Generated by Django 4.2.7 on 2023-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_imageyaab_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCreditoGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_participante', models.IntegerField(blank=True, null=True)),
                ('monto_credito', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Credito Grupal',
                'verbose_name_plural': 'Creditos Grupales',
            },
        ),
    ]
