# Generated by Django 4.2.7 on 2023-12-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_productocreditogrupal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontoGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_grupal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_personas', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
