# Generated by Django 4.2.7 on 2023-12-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_montogrupal_numberperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocreditogrupal',
            name='monto_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numero_participantes', to='dashboard.montogrupal'),
        ),
        migrations.AlterField(
            model_name='productocreditogrupal',
            name='numero_participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numero_participantes', to='dashboard.numberperson'),
        ),
    ]
