# Generated by Django 4.2.7 on 2023-12-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_productocreditogrupal_monto_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocreditogrupal',
            name='monto_credito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocreditogrupal',
            name='numero_participante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
