# Generated by Django 4.2.7 on 2024-02-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_plazo_nombre_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulador',
            name='tipo_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_credito', to='dashboard.plazo'),
        ),
    ]
