# Generated by Django 4.2.7 on 2024-02-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_prestamo_pago_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='pago_mensual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
