# Generated by Django 4.2.7 on 2024-02-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_prestamo_pago_mensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimuladorPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_credito', to='dashboard.prestamo')),
            ],
            options={
                'verbose_name': 'Prueba simulador',
                'verbose_name_plural': 'Pruebas simulador',
            },
        ),
    ]
