# Generated by Django 4.2.7 on 2024-02-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_rename_tipo_prestamo_simuladorprueba_nombre_prestamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprestamo',
            options={'verbose_name': 'Tipo prestamo', 'verbose_name_plural': 'Tipo prestamo'},
        ),
        migrations.RenameField(
            model_name='tipoprestamo',
            old_name='nombre',
            new_name='grupal',
        ),
        migrations.AddField(
            model_name='tipoprestamo',
            name='personal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
