# Generated by Django 4.2.7 on 2024-02-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_periodo_rename_grupal_tipoprestamo_tipo_credito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simuladorprueba',
            options={'verbose_name': 'Simulador prueba', 'verbose_name_plural': 'Simulador pruebas'},
        ),
        migrations.AddField(
            model_name='prestamo',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
