# Generated by Django 4.2.7 on 2024-02-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_simuladorprueba_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='tipo_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.periodo'),
        ),
    ]
