# Generated by Django 4.2.7 on 2024-02-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_prestamo_tipo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='plazo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
