# Generated by Django 4.2.7 on 2024-02-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_prestamo_plazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simuladorprueba',
            name='nombre_prestamo',
        ),
    ]
