# Generated by Django 4.2.7 on 2024-02-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_prestamo_tiempo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='interes',
            new_name='interes_moratorio',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='interes_ordinario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='pago_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
