# Generated by Django 4.2.7 on 2024-02-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_rename_interes_prestamo_interes_moratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuladorprueba',
            name='nombre_prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_credito', to='dashboard.prestamo'),
        ),
    ]
