# Generated by Django 4.2.7 on 2024-02-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_simuladorprueba_nombre_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuladorprueba',
            name='nombre_prestamo_seleccionado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
