# Generated by Django 4.2.7 on 2024-02-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_simuladorprueba_nombre_prestamo_seleccionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simuladorprueba',
            name='nombre_prestamo_seleccionado',
        ),
    ]
