# Generated by Django 4.2.7 on 2024-03-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_simuladorprueba_montos_seleccionados'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaSimula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montos_simulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montos_simulador', to='dashboard.prestamo')),
            ],
            options={
                'verbose_name': 'Montos simulador',
                'verbose_name_plural': 'Montos simulador',
            },
        ),
    ]
