# Generated by Django 4.2.7 on 2024-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_pruebasimula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simuladorprueba',
            name='montos_seleccionados',
        ),
    ]
