# Generated by Django 4.2.7 on 2024-03-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_simuladorprueba_montos_seleccionados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plazo',
            name='nombre_credito',
        ),
    ]
