# Generated by Django 4.2.7 on 2024-03-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_simuladorprueba_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuladorprueba',
            name='solicitud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
