# Generated by Django 4.2.7 on 2024-03-13 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_simuladorprueba_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuladorprueba',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
