# Generated by Django 4.2.7 on 2024-03-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_simuladorprueba_identificador_unico'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPagosModelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='media/')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, null=True)),
                ('simulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulador_unico_pago', to='dashboard.simuladorprueba')),
            ],
            options={
                'verbose_name': 'Registro pago',
                'verbose_name_plural': 'Registros pagos',
            },
        ),
    ]
