# Generated by Django 4.2.7 on 2024-03-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_registropagosmodelos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroPagosModelos',
        ),
    ]
