# Generated by Django 4.2.7 on 2024-02-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocreditos',
            name='monto_credito',
        ),
        migrations.RemoveField(
            model_name='registrocreditos',
            name='pago',
        ),
    ]
