# Generated by Django 4.2.7 on 2024-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_registrocreditos_numero_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocreditos',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
