# Generated by Django 4.2.7 on 2024-02-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_registrocreditos_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocreditos',
            name='monto_total',
        ),
    ]
