# Generated by Django 4.2.7 on 2024-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_estatuscredito_desembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatuscredito',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estatuscredito',
            name='monto_pago_men',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estatuscredito',
            name='numero_de_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatuscredito',
            name='tipo',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
