# Generated by Django 4.2.7 on 2024-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0008_estatuscredito_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatuscredito',
            name='dias_morosidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatuscredito',
            name='estatus',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estatuscredito',
            name='monto_morosidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estatuscredito',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estatuscredito',
            name='saldo_mas_morosidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
