# Generated by Django 4.2.7 on 2024-02-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0009_estatuscredito_dias_morosidad_estatuscredito_estatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPagosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='num_contrato', to='calificaciones.registrocreditos')),
            ],
            options={
                'verbose_name': 'Registro pago',
                'verbose_name_plural': 'Registros pagos',
            },
        ),
    ]
