# Generated by Django 4.2.7 on 2024-02-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0010_registropagosmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagosmodel',
            name='valor_registro_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='num_contrato', to='calificaciones.registrocreditos'),
        ),
        migrations.AlterField(
            model_name='registropagosmodel',
            name='num_contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
