# Generated by Django 4.2.7 on 2024-02-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0011_registropagosmodel_valor_registro_credito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='valor_registro_credito',
        ),
        migrations.AlterField(
            model_name='registropagosmodel',
            name='num_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='num_contrato', to='calificaciones.registrocreditos'),
        ),
    ]
