# Generated by Django 4.2.7 on 2024-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0012_remove_registropagosmodel_valor_registro_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocreditos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='registro_creditos/'),
        ),
        migrations.AddField(
            model_name='registrocreditos',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
