# Generated by Django 4.2.7 on 2024-03-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0013_registrocreditos_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocreditos',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='registrocreditos',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='registrocreditos',
            name='numero_contrato',
        ),
    ]
