# Generated by Django 4.2.7 on 2024-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0014_remove_registrocreditos_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagosmodel',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='registro_creditos/'),
        ),
        migrations.AddField(
            model_name='registropagosmodel',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registropagosmodel',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
