# Generated by Django 4.2.7 on 2024-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0015_registropagosmodel_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagosmodel',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
