# Generated by Django 4.2.7 on 2024-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0016_alter_registropagosmodel_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocreditos',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
