# Generated by Django 4.2.7 on 2024-03-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0017_registrocreditos_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagosmodel',
            name='num_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='num_contrato', to='calificaciones.estatuscredito'),
        ),
    ]
