# Generated by Django 4.2.7 on 2024-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0019_remove_registropagosmodel_numero_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='estatus_num_contrato',
        ),
        migrations.AddField(
            model_name='registropagosmodel',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
