# Generated by Django 4.2.7 on 2024-03-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0020_remove_registropagosmodel_estatus_num_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropagosmodel',
            old_name='monto_total',
            new_name='monto_total_registro',
        ),
    ]
