# Generated by Django 4.2.7 on 2024-03-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0021_rename_monto_total_registropagosmodel_monto_total_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropagosmodel',
            old_name='monto_total_registro',
            new_name='pago_mensual',
        ),
    ]
