# Generated by Django 4.2.7 on 2024-03-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0022_rename_monto_total_registro_registropagosmodel_pago_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagosmodel',
            name='archivo_pago',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pagos/'),
        ),
    ]
