# Generated by Django 4.2.7 on 2024-03-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0024_remove_registropagosmodel_archivo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagosmodel',
            name='numero_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
