# Generated by Django 4.2.7 on 2024-03-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_simuladorprueba_usuario_user'),
        ('calificaciones', '0025_registropagosmodel_numero_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatuscredito',
            name='cliente_estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_estatus', to='dashboard.simuladorprueba'),
        ),
    ]
