# Generated by Django 4.2.7 on 2024-03-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_simuladorprueba_identificador_unico'),
        ('calificaciones', '0026_alter_estatuscredito_cliente_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropagosmodel',
            old_name='documento',
            new_name='comprobante_pago',
        ),
        migrations.RenameField(
            model_name='registropagosmodel',
            old_name='pago_mensual',
            new_name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='num_contrato',
        ),
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='numero_pago',
        ),
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='usuario',
        ),
        migrations.AddField(
            model_name='registropagosmodel',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registropagosmodel',
            name='simulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulador_unico', to='dashboard.simuladorprueba'),
        ),
    ]
