# Generated by Django 4.2.7 on 2024-03-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0027_rename_documento_registropagosmodel_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagosmodel',
            name='numero_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
