# Generated by Django 4.2.7 on 2024-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0028_registropagosmodel_numero_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropagosmodel',
            name='monto_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
