# Generated by Django 4.2.7 on 2024-03-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0029_registropagosmodel_monto_restante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='monto_restante',
        ),
    ]
