# Generated by Django 4.2.7 on 2024-03-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0030_remove_registropagosmodel_monto_restante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropagosmodel',
            name='numero_pago',
        ),
    ]
