# Generated by Django 4.2.7 on 2023-12-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aviso_privacidad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
