# Generated by Django 4.2.7 on 2023-12-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rechazado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
