# Generated by Django 4.2.7 on 2023-12-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_rechazado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solicitud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
