# Generated by Django 4.2.7 on 2023-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curp_texto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
