# Generated by Django 4.2.7 on 2023-12-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_productocreditogrupal'),
        ('users', '0014_correoscreditogrupal'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='monto_vacantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monto_vacantes', to='dashboard.productocreditogrupal'),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='participantes_numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numero_participantes', to='dashboard.productocreditogrupal'),
        ),
    ]
