# Generated by Django 4.2.7 on 2023-12-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_correoscreditogrupal_monto_vacantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoscreditogrupal',
            name='monto_vacantes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
