# Generated by Django 4.2.7 on 2023-12-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_correoscreditogrupal_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='email2',
        ),
    ]
