# Generated by Django 4.2.7 on 2023-12-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_correoscreditogrupal_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
