# Generated by Django 4.2.7 on 2023-12-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_correoscreditogrupal_email2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correoscreditogrupal',
            old_name='email2',
            new_name='segundo_email',
        ),
    ]
