# Generated by Django 4.2.7 on 2023-12-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_correoscreditogrupal_segundo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correoscreditogrupal',
            old_name='email',
            new_name='email_credito_grupal',
        ),
    ]
