# Generated by Django 4.2.7 on 2023-12-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_correoscreditogrupal_date_joined_grupal'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='segundo_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
