# Generated by Django 4.2.7 on 2023-12-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_correoscreditogrupal_segundo_email_grupal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoscreditogrupal',
            name='email_credito_grupal',
            field=models.EmailField(max_length=254),
        ),
    ]
