# Generated by Django 4.2.7 on 2023-12-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_correoscreditogrupal_email_credito_grupal'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='cuarto_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='decimo_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='noveno_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='octavo_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='onceavo_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='quinto_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='septimo_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='sexto_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correoscreditogrupal',
            name='tercero_email_grupal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
