# Generated by Django 4.2.7 on 2024-01-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_correoscreditogrupal_email_credito_grupal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correoscreditogrupal',
            old_name='genero_grupal',
            new_name='celular_coordinador',
        ),
        migrations.RenameField(
            model_name='correoscreditogrupal',
            old_name='email_credito_grupal',
            new_name='correos_participantes',
        ),
        migrations.RenameField(
            model_name='correoscreditogrupal',
            old_name='estado_civil_grupal',
            new_name='names_grupal',
        ),
        migrations.RenameField(
            model_name='correoscreditogrupal',
            old_name='first_name_grupal',
            new_name='surnames_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='cuarto_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='decimo_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='last_name_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='nacionalidad_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='noveno_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='octavo_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='onceavo_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='pais_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='quinto_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='second_name_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='segundo_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='septimo_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='sexto_email_grupal',
        ),
        migrations.RemoveField(
            model_name='correoscreditogrupal',
            name='tercero_email_grupal',
        ),
    ]
