# Generated by Django 4.2.7 on 2024-01-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_genero_grupal_correoscreditogrupal_celular_coordinador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocreditopersonal',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
