# Generated by Django 4.2.7 on 2024-01-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_grupocreditopersonal_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupocreditopersonal',
            old_name='fecha_nac',
            new_name='fecha_nac_grupal',
        ),
    ]
