# Generated by Django 4.2.7 on 2024-01-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_rename_fecha_nac_grupocreditopersonal_fecha_nac_grupal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupocreditopersonal',
            old_name='documento_ine',
            new_name='documento_ine_grupal',
        ),
    ]
