# Generated by Django 4.2.7 on 2024-01-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_rename_documento_ine_grupocreditopersonal_documento_ine_grupal'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocreditopersonal',
            name='firma_digital',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
