# Generated by Django 4.2.7 on 2024-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_grupocreditopersonal_firma_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firma_digital_personal',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firma_imagen_personal',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
