# Generated by Django 4.2.7 on 2024-01-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_grupocreditopersonal_aviso_privacidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupocreditopersonal',
            old_name='aviso_privacidad',
            new_name='aviso_privacidad_grupal',
        ),
        migrations.RenameField(
            model_name='grupocreditopersonal',
            old_name='buro_credito',
            new_name='buro_credito_grupal',
        ),
    ]
