# Generated by Django 4.2.7 on 2024-01-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_rename_aviso_privacidad_grupocreditopersonal_aviso_privacidad_grupal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocreditopersonal',
            name='correos_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correos_credito', to='users.correoscreditogrupal'),
        ),
    ]
