# Generated by Django 4.2.7 on 2024-01-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_productocreditogrupal_monto_credito_and_more'),
        ('users', '0043_grupocreditopersonal_correos_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocreditopersonal',
            name='productocreditogrupal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productocredito', to='dashboard.productocreditogrupal'),
        ),
    ]
