# Generated by Django 4.2.7 on 2024-01-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_user_buro_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivilValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico_estado_civil', models.IntegerField(blank=True, null=True)),
                ('valor_numerico_edad', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
