# Generated by Django 4.2.7 on 2024-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_estadocivilvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
