# Generated by Django 4.2.7 on 2024-01-23 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_user_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='celular',
            new_name='empleo',
        ),
        migrations.AlterField(
            model_name='estadocivilvalues',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
