# Generated by Django 4.2.7 on 2024-01-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_estadocivilvalues_valor_numerico_empleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocivilvalues',
            name='valor_numerico_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
