# Generated by Django 4.2.7 on 2024-01-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_estadocivilvalues_valor_numerico_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_images/'),
        ),
    ]
