# Generated by Django 4.2.7 on 2024-01-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_user_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
