# Generated by Django 4.2.7 on 2024-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_user_simulador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
