# Generated by Django 4.2.7 on 2024-02-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_user_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_proximo_viernes',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
