# Generated by Django 4.2.7 on 2024-02-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_remove_user_fecha_proximo_viernes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_proximo_viernes',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
